### PR TITLE
Feature/groupby

### PR DESCRIPTION
**Pull request by Petaire**

### CODE REVIEW

**Comment by jonenst** [comment]
Hi,
thanks for contributing to this project.

Can you please describe this pull request ?
- What is the new feature ? How can we use it ?
- Why do we need the new feature ?

Regarding the bugfix for "IN management", what is the bug ? When is it triggered, what is the expected result and actual result ?

After we understand better this pull request, we can look into smaller details in the code.

Thanks in advance

**Comment by Petaire** [comment]
The new feature enables the use of SOLR group keyword by adding `&group=true&group.field=<SOLR_FIELD>` in the query parameter.
https://cwiki.apache.org/confluence/display/solr/Result+Grouping

The bug about the IN was that a query like this:
`&fq=place:(place1 OR place2 OR place3)`
 to search for a place IN place1 and so on was formatted and replaced in the plugin by:
`&fq=place:"(place1 OR place2 OR place3)"`
meaning a strict search on the litteral string "(place1 OR place2 OR place3)"

**Comment by jonenst** [comment]
I did some tests:
for ```page=search-solr&query=page``` I get
```
Search results
Number of document found : 2

Type : PAGE(2)

Page 1 -- A child page -- 06/08/2014
Home -- Home Page -- 06/08/2014
Results : 1 - 2
```

for ```page=search-solr&query=page&group=true&group.field=type``` I get
```
Search results
Number of document found : 1

Type -- PAGE(2)

Page 1 -- A child page -- 06/08/2014
Results : 1 - 1
```

Is this the expected result ? Only one document of each group is shown.
The problems I see is that:
  * It says "number of documents found : 1" but should say number of groups of documents.
  * the facet counts show the number of documents but the other counts show the number of groups.
  * It should display more infos on the groups (their sizes for example ?), maybe more than one doc per group, or maybe just the title of all the docs in the group, maybe an ellipsis after 10 titles.

I think we should answer these UI questions before merging this feature. What do you think ?

Thanks in advance,

**Comment by jonenst** [comment]
> The bug about the IN was that a query like this:
&fq=place:(place1 OR place2 OR place3)
to search for a place IN place1 and so on was formatted and replaced in the plugin by:
&fq=place:"(place1 OR place2 OR place3)"
meaning a strict search on the litteral string "(place1 OR place2 OR place3)"

I think this needs a better explanation. You create a new type of Operator ("IN") ? What is the meaning of this operator ? Also, with your patch there is no way to select this operator using the website, you have to edit the database directly to do it.

For the case your describe, you are supposed to use the "OR" operator and do 
&fq=place:place1&fq=place:place2&fq=place3
if you selected the "OR" operator for the field "place", then this correctly generates the following query to solr:
fq=place:("place1" OR "place2" OR "place3")

Do we really need to create a new operator ?

Thanks in advance,
Jon

**Comment by jonenst** [comment]
So what happened with this ?

**Pull request closed without merging**
